import numpy as np

PI = np.pi

MAX_WALK_ROTATIONAL_SPEED = PI / 10  # in rad/sec
MAX_WALK_SPEED_X = 10  # cm/s
MAX_WALK_SPEED_Y = 10

MAX_HEIGHT_DISPLACEMENT = 12
MAX_X_DISPLACEMENT = 9
MAX_Y_DISPLACEMENT = 9

MAX_ROLL_DISPLACEMENT = PI / 10
MAX_PITCH_DISPLACEMENT = PI / 10
MAX_YAW_DISPLACEMENT = PI / 10
