import numpy as np

PI = np.pi

MAX_WALK_ROTATIONAL_SPEED = PI / 10  # in rad/sec
MAX_WALK_SPEED_X = 15  # cm/s
MAX_WALK_SPEED_Y = 15

MAX_HEIGHT_DISPLACEMENT = 15
MAX_X_DISPLACEMENT = 12
MAX_Y_DISPLACEMENT = 12

MAX_ROLL_DISPLACEMENT = PI / 10
MAX_PITCH_DISPLACEMENT = PI / 10
